user: |md
  **User**

  [Person]

  Retail investors of all experience levels
|
user.shape: rectangle

frontend: |md
  **Frontend**

  [Software System]
  
  Primarily a data display and interface, used by users to communicate with the <br />
  backend
|
frontend.shape: rectangle

backend: |md
  **Backend**

  [Software System]
  
  Hosts and serves user data and queries data from external APIs on behalf of <br />
  the entire set of users; performs and runs analyses requests by users.
|
backend.shape: rectangle

user <-> frontend
frontend <-> backend