News Tab: {
	nv: News View
	nq: New Query (Dialog)

	nv -> nq
}

Watchlist Tab: {
	wv: Watchlist View
	at: Add Ticker to Watchlist (Dialog)
	itv: Individual Ticker View
	ah: Add Holding to Ticker (Dialog)

	wv -> itv
	wv -> at
	itv -> ah
}

Analysis Tab: {
	unimplemented
}

